safe: true
permalink: /:title.html
exclude: [ assets ]
markdown: kramdown

default_theme: yandex
default_width: 792
default_lang: ru
default_body_class: list

kramdown:
  enable_coderay: false

author:
    name: MIke mellior@
    position: Home-page developer
    company:
        name: Яндекс
        url:  http://www.yandex.ru/

progress: true
